version = 0.1

[default]
[default.global.parameters]
stack_name = "serverless-observability-demo"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
s3_prefix = "serverless-observability-demo"
confirm_changeset = true
resolve_s3 = true
# parameter_overrides = "Environment=\"demo\" NotificationEmail=\"serverless-observability-demo@mailinator.com\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"